modules:
  prereg:
    enabled: false
    image:
      repository: mosipid/apitest-prereg
      tag: 1.3.0-beta.1
      pullPolicy: Always
  masterdata:
    enabled: false
    image:
      repository: mosipid/apitest-masterdata
      tag: 1.3.0-beta.1
      pullPolicy: Always
  idrepo:
    enabled: false
    image:
      repository: mosipid/apitest-idrepo
      tag: 1.3.0-beta.1
      pullPolicy: Always
  partner:
    enabled: false
    image:
      repository: mosipid/apitest-pms
      tag: 1.2.2.0
      pullPolicy: Always
  resident:
    enabled: false
    image:
      repository: mosipid/apitest-resident
      tag: 1.3.0-beta.2
      pullPolicy: Always
  auth:
    enabled: false
    image:
      repository: mosipid/apitest-auth
      tag: 1.3.0-beta.1
      pullPolicy: Always
  esignet:
    enabled: false
    image:
      repository: mosipid/apitest-esignet
      tag: 1.5.1
      pullPolicy: Always
  mimoto:
    enabled: false
    image:
      repository: mosipid/apitest-mimoto
      tag: 0.15.2
      pullPolicy: Always
  injicertify:
    enabled: false
    image:
      repository: mosipid/apitest-inji-certify
      tag: 0.10.2
      pullPolicy: Always
  injiverify:
    enabled: false
    image:
      repository: mosipqa/apitest-inji-verify
      tag: develop
      pullPolicy: Always
  esignet-signup:
    enabled: false
    image:
      repository: mosipid/apitest-esignet-signup
      tag: 1.1.1
      pullPolicy: Always      
  variables:
    push_reports_to_s3: "yes"
