modules:
  - name: admin-ui
    enabled: false
    image:
      registry: docker.io
      repository: mosipqa/uitest-admin
      tag: develop
      pullPolicy: Always
  - name: pmp-ui
    enabled: false
    image:
      registry: docker.io
      repository: mosipid/uitest-pmp
      tag: 1.2.2.0
      pullPolicy: Always
  - name: resident-ui
    enabled: false
    image:
      registry: docker.io
      repository: mosipqa/uitest-resident
      tag: develop
      pullPolicy: Always
